version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: dockerfiles/app.dockerfile
    environment:
      DATABASE_URI: postgresql://postgres:postgres@db_test:5432/web_test
    depends_on:
      - db_test

  db_test:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_test
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_test_data:
