services:
  app_base:
    build:
      context: ..
      dockerfile: dockerfiles/app.dockerfile
    volumes:
      - ..:/workspace:cached
    env_file:
      - ../.env

  db_base:
    build:
      context: ..
      dockerfile: dockerfiles/db.dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgres-data: