include:
  - docker-compose.base.yml

services:
  web:
    extends:
      file: docker-compose.base.yml
      service: app_base
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    container_name: fastapi-app
    ports:
      - 8002:8000
    depends_on:
      web-db:
        condition: service_healthy

  web-db:
    extends:
      file: docker-compose.base.yml
      service: db_base
    container_name: fastapi-db
    expose:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
