services:
  app:
    build:
      context: ..
      dockerfile: dockerfiles/app.dockerfile
    volumes:
      - ..:/workspace:cached
    env_file:
      - ../.env
    command: sleep infinity
    depends_on:
      - web-db
      - web-test-db

  web-db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: web

  web-test-db:
    image: postgres:15
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: web_test

volumes:
  postgres-data:
